### ISSUE TITLE
Errors on missing modules and EventEmitter not being a function?

### ISSUE THREAD

**Issue by operatorjen** [mikeal/peer-room#1]
Missing modules error on the server for: emitter-component and props

Getting this error after I installed the missing modules above (both in Chrome Canary and Firefox Nightly):
Uncaught TypeError: Emitter is not a function in array.js

I don't get these errors on your production version but only locally. Any ideas?

**Comment by mikeal** [comment]
Ya, I had to patch this locally because it's a weird try/catch require that doesn't work through browserify.

I've fixed it permanently by removing that terrible dep from funky :)

**Comment by mikeal** [comment]
FYI, this was the fix https://github.com/mikeal/peer-room/commit/e73b5b9bbea40f3c7a848d0128081be77e1a0333
